version: '3.8'
services:
  nodejsserver:
    image: rnseminarcnpm2.azurecr.io/seminarcnpmbackendnodejsserver:latest
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - redis
#     - mongo
      - pythonserver
    environment:
      ONE_SIGNAL_AUTH_KEY: os_v2_app_tlvcluppzvcxrh5n77vuagxgj3fugsltvheu4snbyzctvkv6splqqjay4uzjhdoua3prjpr67lnaj67aanze26i5s6hzvm6epcy7pca
      ONE_SIGNAL______KEY: os_v2_app_tlvcluppzvcxrh5n77vuagxgj3fugsltvheu4snbyzctvkv6splqqjay4uzjhdoua3prjpr67lnaj67aanze26i5s6hzvm6epcy7pca
      JWT_SECRET_KEY: LaughOutLoud
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb+srv://root:123@cluster0.ppxonhm.mongodb.net/lift?retryWrites=true&w=majority&appName=Cluster0
  redis:
    image: redis/redis-stack:7.0.6-RC9
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
# mongo:
#   image: mongodb/mongodb-atlas-local:latest
#   ports:
#     - "27017:27017"
#   environment:
#     - MONGODB_INITDB_ROOT_USERNAME=user
#     - MONGODB_INITDB_ROOT_PASSWORD=pass
#   volumes:
#     - mongo-data:/data/db
#     - mgcfg-data:/data/configdb

  pythonserver:
    image: rnseminarcnpm2.azurecr.io/seminarcnpmbackendpythonserver:latest
    build:
      context: ./pythonClient
      dockerfile: Dockerfile
    ports:
      - "27018:27018"
      -             "5200:5200"
    depends_on:
      - redis
#     - mongo
    environment:
      ONE_SIGNAL_AUTH_KEY: os_v2_app_tlvcluppzvcxrh5n77vuagxgj3fugsltvheu4snbyzctvkv6splqqjay4uzjhdoua3prjpr67lnaj67aanze26i5s6hzvm6epcy7pca
      ONE_SIGNAL______KEY: os_v2_app_tlvcluppzvcxrh5n77vuagxgj3fugsltvheu4snbyzctvkv6splqqjay4uzjhdoua3prjpr67lnaj67aanze26i5s6hzvm6epcy7pca      
      OPEN_AI_API_KEY: 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
      COHERE_API_KEY:  s1v4UzmYNozCzM6gX5NGQmK4Ld1kLTjlB3MphF8t
      COLLAB_API_KEY:     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
      MONGO_DB : mongodb+srv://root:123@cluster0.ppxonhm.mongodb.net/lift?retryWrites=true&w=majority&appName=Cluster0
      GOOGLE_MAP_API:  668551c9e921e378819210twyca5b8f
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb+srv://root:123@cluster0.ppxonhm.mongodb.net/lift?retryWrites=true&w=majority&appName=Cluster0
      MOMO_ACCESS_KEY: F8BBA842ECF85
      MOMO_SECRET_KEY: K951B6PE1waDMi640xX08PD3vg6EkVlz
      REDIRECT_URL: clientApp://payment
      IPN_URL     :     https://webhook.site/b3088a6a-2d17-4f8d-a383-71389a6c600b
      PAYMENT_CODE: 'T8Qii53fAXyUftPV3m9ysyRhEanUs9KlOPfHgpMR0ON50U10Bh+vZdpJU7VY4z+Z2y77fJHkoDc69scwwzLuW5MzeUKTwPo3ZMaB29imm6YulqnWfTkgzqRaion+EuD7FN9wZ4aXE1+mRt0gHsU193y+yxtRgpmY7SDMU9hCKoQtYyHsfFR5FUAOAKMdw2fzQqpToei3rnaYvZuYaxolprm9+/+WIETnPUDlxCYOiw7vPeaaYQQH0BF0TxyU3zu36ODx980rJvPAgtJzH1gUrlxcSS1HQeQ9ZaVM1eOK/jl8KJm6ijOwErHGbgf/hVymUQG65rHU2MWz9U8QUjvDWA=='
      MOMO_HOSTNAME: test-payment.momo.vn
      PORT         : 3000

volumes:
  redis-data:
# mongo-data:
# mgcfg-data:




