version: '3.8'
services:
  nodejsserver:
    image: rnseminarcnpm.azurecr.io/seminarcnpmbackendnodejserver:latest
    build: .
    ports:
      - "8088:8080"
    depends_on:
      - redis
      - mongo
    environment:
      JWT_SECRET_KEY: LaughOutLoud
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://user:pass@mongo:27017/?directConnection=true
  redis:
    image: redis/redis-stack:7.0.6-RC9
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  mongo:
    image: mongodb/mongodb-atlas-local:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo-data:/data/db
      - mgcfg-data:/data/configdb
  mongosh:
    image: rtsp/mongosh:latest
    ports:
      - "1234:1234"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://user:pass@mongo:27017/?directConnection=true


  server:
    build:
      context: ./pythonClient
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./pythonClient:/usr/src/app
      - server-data:/data/db
    depends_on:
      - redis
      - mongo
    environment:
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://mongo:27017/?directConnection=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  redis-data:
  mongo-data:
  mgcfg-data:

















