version: '3.8'
services:
  app:
    image: rnseminarcnpm.azurecr.io/seminarcnpmbackend:latest
    build: .
    ports:
      - "8088:8080"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
  redis:
    image: redis/redis-stack:7.0.6-RC9
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:










