version: '3.8'
services:
  app:
    image: rnseminarcnpm.azurecr.io/seminarcnpmbackend:latest
    build: .
    ports:
      - "8088:8080"
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:


