version: '3.8'
services:
  nodejsserver:
    image: rnseminarcnpm2.azurecr.io/seminarcnpmbackendnodejsserver:latest
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - redis
#     - mongo
      - pythonserver
    environment:
      JWT_SECRET_KEY: LaughOutLoud
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb+srv://root:123@cluster0.ppxonhm.mongodb.net/lift?retryWrites=true&w=majority&appName=Cluster0
  redis:
    image: redis/redis-stack:7.0.6-RC9
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
# mongo:
#   image: mongodb/mongodb-atlas-local:latest
#   ports:
#     - "27017:27017"
#   environment:
#     - MONGODB_INITDB_ROOT_USERNAME=user
#     - MONGODB_INITDB_ROOT_PASSWORD=pass
#   volumes:
#     - mongo-data:/data/db
#     - mgcfg-data:/data/configdb

  pythonserver:
    image: rnseminarcnpm2.azurecr.io/seminarcnpmbackendpythonserver:latest
    build:
      context: ./pythonClient
      dockerfile: Dockerfile
    ports:
      - "27018:27018"
      -             "5200:5200"
    depends_on:
      - redis
#     - mongo
    environment:
      OPEN_AI_API_KEY: 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
      COHERE_API_KEY:  s1v4UzmYNozCzM6gX5NGQmK4Ld1kLTjlB3MphF8t
      COLLAB_API_KEY:     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
      MONGO_DB : mongodb+srv://root:123@cluster0.ppxonhm.mongodb.net/lift?retryWrites=true&w=majority&appName=Cluster0
      GOOGLE_MAP_API:  668551c9e921e378819210twyca5b8f
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb+srv://root:123@cluster0.ppxonhm.mongodb.net/lift?retryWrites=true&w=majority&appName=Cluster0

volumes:
  redis-data:
# mongo-data:
# mgcfg-data:




